* Session 2020-11-30 7a849c156b2f23bfdb8cd8d324f6a2de792a56a1
+ TODO: the map menu gets really hard to read at big resolutions
  - buttons get spaced out
  - hard to tell which "GO" correlated with which button
+ TODO: ESCAPE should close the map
+ FIXED: Eventually the scroll in the event log freezes
+ TODO: Destroyer seems to fire, but the shot hangs (are they in the same tick as player?)
+ TODO: I could really use an "autoloot sector" button!
+ FIXED: I think...it broke when I took up to my limit in items? yep, InventoryFullCannotStoreException
  - I could use a readout on inventory size, that seems helpful
+ Well game crashed, I'll patch that and continue
+ fixed, confirmed
+ TODO: sometimes cutting beam laser finishes SO FAST you don't even see it
  - basically if you're right up next to a guy
  - this is probably the same with a shot that hits you as you're right next to something
  - fix that Tween timing issue?
+ TODO: even the inventory doesn't tell you how many slots you have left, that's definitely bad
+ TODO: inventory still has TODO: item descriptions, rip
+ TODO: there are white squares for...I think items that you've picked up? that vanish when you enter sight
+ TODO: FoW resets when you load
+ FIXED: projectile paths not drawn when you load
+ TODO: newly picked-up items go to the last column in the inventory?
  - if you use an item in the left column then pick an item up it goes to the right?
+ TODO: you can't hold down button to scroll your menu buttons...annoying!
+ TODO: intel doesn't auto-use which is annoying
+ TODO: path danger doesn't take into account collision
+ ending for now ~level 5
+ playing more
+ it'd be really sweet if the readout told you when you picked items up
+ TODO: right...I have the seed the same for every level. should fix that.
+ TODO: carriers are pretty lol to fight, prioritize enemies that you can kill in one hit?
+ TODO: it doesn't tell you what sector you're in anywhere except for the starting log scroll
+ Approaching Infinity has its log reversed (new entries at top) - uh. wait. what's standard?
+ FIXED: somehow switching levels keeps the danger map from previous level...?
  - ah! it went away after switching to the save screen
  - probably is: jump under fire doesn't clear danger map properly
+ TODO: jump point can spawn under satellite lol
  - well THAT killed my run, RIP run
+ EMP disable is ABSURDLY long on some of the higher-tier enemies
  - Destroyer in particular

* Session 2020-12-02 3a6c655cd26edb289da3390d656770784c737837
+ TODO: crash with NPE:
E 0:01:11.273   void SpaceDodgeRL.library.encounter.rulebook.Rulebook.Attack(SpaceDodgeRL.scenes.entities.Entity , SpaceDodgeRL.scenes.entities.Entity , SpaceDodgeRL.scenes.encounter.state.EncounterState ): System.NullReferenceException: Object reference not set to an instance of an object.
  <C++ Error>   Unhandled exception
  <C++ Source>  C:\Users\Travis Moy\Projects\Godot\SpaceDodgeRL\library\encounter\rulebook\Rulebook.cs:124 @ void SpaceDodgeRL.library.encounter.rulebook.Rulebook.Attack(SpaceDodgeRL.scenes.entities.Entity , SpaceDodgeRL.scenes.entities.Entity , SpaceDodgeRL.scenes.encounter.state.EncounterState )()
  <Stack Trace> Rulebook.cs:124 @ void SpaceDodgeRL.library.encounter.rulebook.Rulebook.Attack(SpaceDodgeRL.scenes.entities.Entity , SpaceDodgeRL.scenes.entities.Entity , SpaceDodgeRL.scenes.encounter.state.EncounterState )()
                Rulebook.cs:152 @ Boolean SpaceDodgeRL.library.encounter.rulebook.Rulebook.ResolveMove(SpaceDodgeRL.library.encounter.rulebook.actions.MoveAction , SpaceDodgeRL.scenes.encounter.state.EncounterState )()
                Rulebook.cs:18 @ Boolean SpaceDodgeRL.library.encounter.rulebook.Rulebook+<>c.<.cctor>b__17_2(SpaceDodgeRL.library.encounter.rulebook.EncounterAction , SpaceDodgeRL.scenes.encounter.state.EncounterState )()
                Rulebook.cs:31 @ Boolean SpaceDodgeRL.library.encounter.rulebook.Rulebook.ResolveAction(SpaceDodgeRL.library.encounter.rulebook.EncounterAction , SpaceDodgeRL.scenes.encounter.state.EncounterState )()
                Rulebook.cs:51 @ void SpaceDodgeRL.library.encounter.rulebook.Rulebook+<>c__DisplayClass3_0.<ResolveActionsAndEndTurn>b__0(SpaceDodgeRL.library.encounter.rulebook.EncounterAction )()
                :0 @ void System.Collections.Generic.List`1[[SpaceDodgeRL.library.encounter.rulebook.EncounterAction, SpaceDodgeRL, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ForEach(System.Action`1[SpaceDodgeRL.library.encounter.rulebook.EncounterAction] )()
                Rulebook.cs:51 @ void SpaceDodgeRL.library.encounter.rulebook.Rulebook.ResolveActionsAndEndTurn(System.Collections.Generic.List`1[SpaceDodgeRL.library.encounter.rulebook.EncounterAction] , SpaceDodgeRL.scenes.encounter.state.EncounterState )()
                EncounterRunner.cs:177 @ void SpaceDodgeRL.scenes.encounter.EncounterRunner.RunTurn(SpaceDodgeRL.scenes.encounter.state.EncounterState , SpaceDodgeRL.scenes.InputHandler )()
                EncounterRunner.cs:28 @ void SpaceDodgeRL.scenes.encounter.EncounterRunner._Process(Single )()
+ error cause:
  - immediately go to zone 6 every time
  - travel up
  - at sector ~6? the one with destroyers, kill [something]?
  - get error in - OH! OK
+ error reason: `projectileSource` was null?
  - OH! ok: if an entity gets destroyed, but then their bullet kills something after they're destroyed, it will error out, because they'll be out of the State map!
